inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - vendor/**/*
  DefaultFormatter: simple

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/ParallelAssignment:
  Enabled: false
